// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWOlBCZrdooS8ZQRy4aGLhpJYWIMScvfY',
    appId: '1:4192609097:web:6965d209cc1d8ed7a9b098',
    messagingSenderId: '4192609097',
    projectId: 'mylist-dad1a',
    authDomain: 'mylist-dad1a.firebaseapp.com',
    storageBucket: 'mylist-dad1a.appspot.com',
    measurementId: 'G-SMD5G35PL1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_AQysqiR4hKpC8scPLyU3KtgNFF08k-c',
    appId: '1:4192609097:android:01d4524baf77c59ca9b098',
    messagingSenderId: '4192609097',
    projectId: 'mylist-dad1a',
    storageBucket: 'mylist-dad1a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxF5d07AYC5dJxx2PvYvcy2CydeppZcjk',
    appId: '1:4192609097:ios:6d8a5bd301038c05a9b098',
    messagingSenderId: '4192609097',
    projectId: 'mylist-dad1a',
    storageBucket: 'mylist-dad1a.appspot.com',
    iosBundleId: 'com.example.punyaOrang',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxF5d07AYC5dJxx2PvYvcy2CydeppZcjk',
    appId: '1:4192609097:ios:6d8a5bd301038c05a9b098',
    messagingSenderId: '4192609097',
    projectId: 'mylist-dad1a',
    storageBucket: 'mylist-dad1a.appspot.com',
    iosBundleId: 'com.example.punyaOrang',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWOlBCZrdooS8ZQRy4aGLhpJYWIMScvfY',
    appId: '1:4192609097:web:5096bbfc03fa34eea9b098',
    messagingSenderId: '4192609097',
    projectId: 'mylist-dad1a',
    authDomain: 'mylist-dad1a.firebaseapp.com',
    storageBucket: 'mylist-dad1a.appspot.com',
    measurementId: 'G-0Q6SX2ZEFR',
  );
}
